# Generated by Django 5.2.15 on 2026-07-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_pendingaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='bot_type',
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
