# Generated by Django 5.0.6 on 2026-07-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_sync_pendingaction_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingaction',
            name='bot_type',
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='tool_name',
            field=models.CharField(max_length=100),
        ),
    ]
