# Generated by Django 5.2.15 on 2026-07-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Stationery', 'Stationery'), ('Sports', 'Sports'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
