# Generated by Django 5.0.6 on 2026-07-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_inventory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='assigned_to_room',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
