# Generated by Django 5.2.15 on 2026-07-13 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classsection_default_room'),
        ('accounts', '0006_studentprofile_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='teacher_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_incharge', to='accounts.teacherprofile'),
        ),
    ]
