# Generated by Django 5.0.6 on 2026-06-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='cnic',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
