# Generated by Django 5.2.15 on 2026-07-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_parentprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
