"""
COMMUNICATION APP
=================
System notifications and social-media campaign logs (posts dispatched via
Make.com to Facebook/LinkedIn).

Cross-app references used in this file:
- Notification.sender / receiver, MediaCampaignLog.created_by_admin -> accounts.User
"""

from django.db import models


class Notification(models.Model):
    TYPE_CHOICES = (("in_app", "In-App"), ("email", "Email"), ("whatsapp", "WhatsApp"))

    sender = models.ForeignKey(
        "accounts.User", on_delete=models.SET_NULL, null=True, related_name="notifications_sent"
    )
    receiver = models.ForeignKey(
        "accounts.User", on_delete=models.CASCADE, related_name="notifications_received"
    )
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, default="in_app")
    message = models.TextField()

    # Generic pointer to whatever triggered this notification (a Fee, an
    # Assignment, an Event, etc). Plain fields are sufficient for
    # read-only display; switch to Django's GenericForeignKey only if you
    # later need to select_related() straight to the target object.
    reference_type = models.CharField(max_length=50, blank=True, null=True)
    reference_id = models.PositiveIntegerField(blank=True, null=True)

    is_read = models.BooleanField(default=False, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.sender.email} → {self.receiver.email} ({self.type})"
    class Meta:
        indexes = [models.Index(fields=["receiver", "is_read"])]


class MediaCampaignLog(models.Model):
    """Record of social posts generated by the Media Bot and pushed via Make.com."""

    PLATFORM_CHOICES = (("facebook", "Facebook"), ("linkedin", "LinkedIn"))
    STATUS_CHOICES = (("draft", "Draft"), ("published", "Published"), ("failed", "Failed"))

    post_content = models.TextField()
    post_type = models.CharField(max_length=50, blank=True)  # e.g. 'achievement', 'event', 'general'
    platform = models.CharField(max_length=20, choices=PLATFORM_CHOICES, default="facebook")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="draft")  # result of the Make.com webhook call
    created_by_admin = models.ForeignKey(
        "accounts.User", on_delete=models.SET_NULL, null=True, related_name="campaigns_created"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.platform} - {self.status} ({self.created_at})"